/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.x.product.reviews;  
@SuppressWarnings("all")
/** **********************************
	* TOPICS/MESSAGES 
	************************************ */
public class GetProductReviewsMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"GetProductReviewsMessage\",\"namespace\":\"com.x.product.reviews\",\"doc\":\"**********************************\n\t* TOPICS/MESSAGES \n\t************************************\",\"fields\":[{\"name\":\"product_id\",\"type\":\"string\"}],\"topic\":\"/product/reviews/find\"}");
  public java.lang.CharSequence product_id;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return product_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: product_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
