/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.x.product.reviews;  
@SuppressWarnings("all")
public class IndividualReview extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"IndividualReview\",\"namespace\":\"com.x.product.reviews\",\"fields\":[{\"name\":\"review\",\"type\":\"string\"},{\"name\":\"by\",\"type\":\"string\"},{\"name\":\"date\",\"type\":\"string\"},{\"name\":\"rating\",\"type\":[\"null\",\"int\"]}]}");
  public java.lang.CharSequence review;
  public java.lang.CharSequence by;
  public java.lang.CharSequence date;
  public java.lang.Integer rating;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return review;
    case 1: return by;
    case 2: return date;
    case 3: return rating;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: review = (java.lang.CharSequence)value$; break;
    case 1: by = (java.lang.CharSequence)value$; break;
    case 2: date = (java.lang.CharSequence)value$; break;
    case 3: rating = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
