/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.x.product.reviews;  
@SuppressWarnings("all")
public class ProductDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"ProductDetails\",\"namespace\":\"com.x.product.reviews\",\"fields\":[{\"name\":\"productId\",\"type\":{\"type\":\"record\",\"name\":\"StandardProductId\",\"fields\":[{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"StandardProductIdType\",\"symbols\":[\"UPC\",\"SKU\",\"EAN\",\"MPN\",\"ASIN\",\"ISBN\"]}},{\"name\":\"value\",\"type\":\"string\"}]}},{\"name\":\"reviews\",\"type\":{\"type\":\"record\",\"name\":\"ReviewCollection\",\"fields\":[{\"name\":\"ratingCount\",\"type\":\"int\"},{\"name\":\"average\",\"type\":\"float\"},{\"name\":\"bestRating\",\"type\":[\"null\",\"int\"]},{\"name\":\"worstRating\",\"type\":[\"null\",\"int\"]},{\"name\":\"collection\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"IndividualReview\",\"fields\":[{\"name\":\"review\",\"type\":\"string\"},{\"name\":\"by\",\"type\":\"string\"},{\"name\":\"date\",\"type\":\"string\"},{\"name\":\"rating\",\"type\":[\"null\",\"int\"]}]}}}]}}]}");
  public com.x.product.reviews.StandardProductId productId;
  public com.x.product.reviews.ReviewCollection reviews;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productId;
    case 1: return reviews;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productId = (com.x.product.reviews.StandardProductId)value$; break;
    case 1: reviews = (com.x.product.reviews.ReviewCollection)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
