/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.x.product.reviews;  
@SuppressWarnings("all")
public class ReviewCollection extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"ReviewCollection\",\"namespace\":\"com.x.product.reviews\",\"fields\":[{\"name\":\"ratingCount\",\"type\":\"int\"},{\"name\":\"average\",\"type\":\"float\"},{\"name\":\"bestRating\",\"type\":[\"null\",\"int\"]},{\"name\":\"worstRating\",\"type\":[\"null\",\"int\"]},{\"name\":\"collection\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"IndividualReview\",\"fields\":[{\"name\":\"review\",\"type\":\"string\"},{\"name\":\"by\",\"type\":\"string\"},{\"name\":\"date\",\"type\":\"string\"},{\"name\":\"rating\",\"type\":[\"null\",\"int\"]}]}}}]}");
  public int ratingCount;
  public float average;
  public java.lang.Integer bestRating;
  public java.lang.Integer worstRating;
  public java.util.List<com.x.product.reviews.IndividualReview> collection;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ratingCount;
    case 1: return average;
    case 2: return bestRating;
    case 3: return worstRating;
    case 4: return collection;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ratingCount = (java.lang.Integer)value$; break;
    case 1: average = (java.lang.Float)value$; break;
    case 2: bestRating = (java.lang.Integer)value$; break;
    case 3: worstRating = (java.lang.Integer)value$; break;
    case 4: collection = (java.util.List<com.x.product.reviews.IndividualReview>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
