/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.x.product.reviews;  
@SuppressWarnings("all")
public class StandardProductId extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"StandardProductId\",\"namespace\":\"com.x.product.reviews\",\"fields\":[{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"StandardProductIdType\",\"symbols\":[\"UPC\",\"SKU\",\"EAN\",\"MPN\",\"ASIN\",\"ISBN\"]}},{\"name\":\"value\",\"type\":\"string\"}]}");
  public com.x.product.reviews.StandardProductIdType type;
  public java.lang.CharSequence value;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type = (com.x.product.reviews.StandardProductIdType)value$; break;
    case 1: value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
