/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.x.product.reviews;  
@SuppressWarnings("all")
public enum StandardProductIdType { 
  UPC, SKU, EAN, MPN, ASIN, ISBN  ;
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"enum\",\"name\":\"StandardProductIdType\",\"namespace\":\"com.x.product.reviews\",\"symbols\":[\"UPC\",\"SKU\",\"EAN\",\"MPN\",\"ASIN\",\"ISBN\"]}");
}
